# Generated by Django 6.1.1 on 2026-09-05 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('crop', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField()),
                ('symptoms', models.TextField(help_text='Visible symptoms on foliage, stems, or fruit')),
                ('organic_treatment', models.TextField(help_text='Organic, bio-friendly treatments')),
                ('chemical_treatment', models.TextField(help_text='Conventional chemical treatments and fungicides')),
                ('prevention_tips', models.TextField(help_text='Cultural and preventive farm practices')),
                ('severity_level', models.CharField(choices=[('healthy', 'Healthy (No Disease)'), ('mild', 'Mild Severity'), ('moderate', 'Moderate Severity'), ('severe', 'Severe / High Risk')], default='moderate', max_length=20)),
                ('image_sample', models.CharField(blank=True, default='', help_text='Sample image URL or filename', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['crop', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='leaf_scans/')),
                ('predicted_disease_name', models.CharField(max_length=200)),
                ('crop', models.CharField(blank=True, default='', max_length=100)),
                ('confidence', models.FloatField(help_text='Confidence percentage (0 - 100)')),
                ('is_healthy', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='diseases.disease')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
