# Generated by Django 6.1.1 on 2026-09-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disease',
            options={'ordering': ['crop', 'plant_part', 'name']},
        ),
        migrations.AddField(
            model_name='disease',
            name='plant_part',
            field=models.CharField(choices=[('leaf', 'Leaf / Foliage'), ('stem', 'Stem / Stalk / Vine'), ('root', 'Root / Tuber'), ('fruit', 'Fruit / Pod'), ('whole_plant', 'Whole Plant / General')], default='leaf', help_text='Target plant organ: leaf, stem, root, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='detected_plant_part',
            field=models.CharField(default='leaf', help_text='Detected plant part: leaf, stem, root, unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='is_valid_plant_image',
            field=models.BooleanField(default=True, help_text='True if Stage 1 confirmed valid plant part'),
        ),
    ]
