# Generated by Django 6.1.1 on 2026-09-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_alter_disease_options_disease_plant_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='scientific_name',
            field=models.CharField(blank=True, default='', help_text='Botanical scientific name', max_length=150),
        ),
        migrations.AlterField(
            model_name='disease',
            name='plant_part',
            field=models.CharField(choices=[('leaf', 'Leaf / Foliage 🌿'), ('stem', 'Stem / Stalk / Vine 🎋'), ('root', 'Root / Tuber 🥕'), ('flower', 'Flower / Blossom 🌸'), ('fruit', 'Fruit / Pod 🍎'), ('whole_plant', 'Whole Plant / General 🪴')], default='leaf', help_text='Target plant organ: leaf, stem, root, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='detected_plant_part',
            field=models.CharField(default='leaf', help_text='Detected plant part: leaf, stem, root, flower, fruit, unknown', max_length=50),
        ),
    ]
