# Generated by Django 6.1.1 on 2026-09-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0003_scanhistory_scientific_name_alter_disease_plant_part_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantTaxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('plant_category', models.CharField(choices=[('tree', 'Tree (மரம்)'), ('shrub', 'Shrub / Bush (புதர்ச்செடி)'), ('herb', 'Herb / Annual (மூலிகை / சிறுசெடி)'), ('climber', 'Climber / Vine / Creeper (கொடி)'), ('succulent', 'Succulent / Cactus (கற்றாழை)'), ('grass', 'Grass / Cereal (புல் / தானியம்)')], default='herb', max_length=30)),
                ('typical_parts_available', models.JSONField(default=list, help_text="List of biologically realistic plant parts (e.g. ['leaf', 'stem', 'flower', 'fruit', 'seed'])")),
                ('scientific_name', models.CharField(blank=True, default='', max_length=150)),
                ('tamil_name', models.CharField(blank=True, default='', max_length=150)),
                ('growth_habit', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plant Taxonomy',
                'verbose_name_plural': 'Plant Taxonomies',
                'ordering': ['species_name'],
            },
        ),
        migrations.AlterField(
            model_name='disease',
            name='plant_part',
            field=models.CharField(choices=[('leaf', 'Leaf / Foliage 🌿'), ('stem', 'Stem / Stalk / Vine 🎋'), ('root', 'Root / Tuber 🥕'), ('flower', 'Flower / Blossom 🌸'), ('fruit', 'Fruit / Pod 🍎'), ('seed', 'Seed / Grain / Kernel 🌰'), ('whole_plant', 'Whole Plant / General 🪴')], default='leaf', help_text='Target plant organ: leaf, stem, root, etc.', max_length=50),
        ),
    ]
