# Generated by Django 6.1.1 on 2026-09-07 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0004_planttaxonomy_alter_disease_plant_part'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantPartDiseaseMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(db_index=True, max_length=200)),
                ('crop', models.CharField(db_index=True, max_length=100)),
                ('valid_plant_part', models.CharField(choices=[('leaf', 'Leaf / Foliage 🌿'), ('stem', 'Stem / Stalk / Vine 🎋'), ('root', 'Root / Tuber 🥕'), ('flower', 'Flower / Blossom 🌸'), ('fruit', 'Fruit / Pod 🍎'), ('seed', 'Seed / Grain / Kernel 🌰'), ('whole_plant', 'Whole Plant / General 🪴')], db_index=True, max_length=50)),
                ('is_pathologically_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plant Part Disease Mapping',
                'verbose_name_plural': 'Plant Part Disease Mappings',
                'ordering': ['crop', 'valid_plant_part', 'disease_name'],
                'unique_together': {('disease_name', 'crop', 'valid_plant_part')},
            },
        ),
        migrations.CreateModel(
            name='PredictionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('input_image_name', models.CharField(blank=True, default='', max_length=255)),
                ('detected_plant_part', models.CharField(max_length=50)),
                ('part_confidence_raw', models.FloatField(default=0.0)),
                ('part_confidence_calibrated', models.FloatField(default=0.0)),
                ('predicted_species', models.CharField(max_length=100)),
                ('species_confidence_raw', models.FloatField(default=0.0)),
                ('species_confidence_calibrated', models.FloatField(default=0.0)),
                ('predicted_disease', models.CharField(max_length=200)),
                ('disease_confidence_raw', models.FloatField(default=0.0)),
                ('disease_confidence_calibrated', models.FloatField(default=0.0)),
                ('final_confidence', models.FloatField(default=0.0)),
                ('calibration_method', models.CharField(default='temperature_scaling', max_length=100)),
                ('taxonomy_check_passed', models.BooleanField(default=True)),
                ('correction_applied', models.BooleanField(default=False)),
                ('correction_reason', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prediction Audit Log',
                'verbose_name_plural': 'Prediction Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
